### ISSUE TITLE
The authentication tag is invalid

### ISSUE THREAD

**Issue by scollovati** [asmw/andOTP-decrypt#12]
I am using andOTP 0.6.3.1 and I created a backup file (AES).
I moved it to my laptop via usb cable or cloud service (Dropbox, ..).

However, when I run 
`python3 andotp_decrypt.py otp_accounts_XXXX.json.aes `

The output is:
```
andOTP AES passphrase:
The authentication tag is invalid.
The passphrase was probably wrong
None
```
Python version 3.6.8 

Beware that after cloning this repo I have already fixed issue https://github.com/asmw/andOTP-decrypt/issues/4

**Comment by asmw** [comment]
Issue #4 should no longer be relevant as pycrypto was deprecated in favor of pycryptodome, can you try with the published version?
Just run `pip install andOTP-decrypt`, it should just work.
You should then have a wrapper `andotp_decrypt` in your pip path.
Please try that

**Comment by asmw** [comment]
I just tried again with a fresh backup made with andOTP 0.6.3.1, it works for me using the published version

**Comment by asmw** [comment]
Another thing you can try is decrypt `accounts_new_123456.json.aes` from the tests folder. It is in the new format and guaranteed to work. Password is 123456 :)

**Comment by scollovati** [comment]
Unfortunately with pip I get
`pip3 install --user andotp-decrypt`
output
```
ERROR: Could not find a version that satisfies the requirement andotp-decrypt (from versions: none)
ERROR: No matching distribution found for andotp-decrypt

```

But if now I clone this repo the scripts work fine :)
