### ISSUE TITLE
How to install pycrypto with AES GCM?

### ISSUE THREAD

**Issue by tomekit** [asmw/andOTP-decrypt#4]
Hi,
I am facing a problem where I am getting:
`ModuleNotFoundError: No module named 'aes_gcm.aes_gcm'`

I've installed the `pycrypto` module using `pip3` however it didn't help.

I've found this thread:
https://stackoverflow.com/questions/7958088/aes-in-gcm-mode-in-python

which confirms that pip version of pycrypto doesn't have GCM. As pycrypto seem to be practically dead project.

I've tried to clone this in the project directory:
https://github.com/bozhu/AES-GCM-Python

Unfortunately I am facing another problem:
andOTP AES passphrase:

> Traceback (most recent call last):
>   File "andotp_decrypt.py", line 62, in <module>
>     print(decrypt_aes(arguments['INPUT_FILE']))
>   File "andotp_decrypt.py", line 48, in decrypt_aes
>     aes = AES_GCM(symmetric_key)
>   File "/home/tomek/Documents/data/andOTP-decrypt/aes_gcm/aes_gcm.py", line 59, in __init__
>     self.change_key(master_key)
>   File "/home/tomek/Documents/data/andOTP-decrypt/aes_gcm/aes_gcm.py", line 62, in change_key
>     if master_key >= (1 << 128):
> TypeError: '>=' not supported between instances of 'bytes' and 'int'

I am not a Python user, so it's not easy for me to set things up. I would appreciate any help in this matter. Thanks !

**Comment by tomekit** [comment]
Right, the problem was that the submodule was not initialised:
`git submodule update --init --recursive`

**Comment by cfcs** [comment]
There's also a dependency on `python3-docopt` missing that doesn't seem to be default on debian.

**Comment by codingtony** [comment]
> Right, the problem was that the submodule was not initialised:
> `git submodule update --init --recursive`

Should be in the README.md

**Comment by mar1ged** [comment]
I used your comments on Ubuntu 19.04 but still receive:

```
Traceback (most recent call last):
  File "./decrypt.py", line 13, in <module>
    from aes_gcm.aes_gcm import AES_GCM, InvalidTagException
ModuleNotFoundError: No module named 'aes_gcm'
```

I tried this to get the missing dependencies:

> sudo apt-get install build-essential libgmp3-dev python3-dev
> sudo apt install python3-pip
> pip3 install cryptography
> pip3 install pycryptodome
> pip3 install cryptography
> pip3 install pycryptodome
> pip3 install pycryptodomex

**Comment by cfcs** [comment]
@mar1ged did you try @tomekit's [suggestion](https://github.com/asmw/andOTP-decrypt/issues/4#issuecomment-418488918) of `git submodule update --init --recursive` from the top-level folder of `andOTP-decrypt`?

After running that command, there should be files in the `aes_gcm/` folder.

If that does not work, you could try:
```shell
rmdir aes_gcm
# if the above command fails: rm -r aes_gcm/

git clone https://github.com/asmw/AES-GCM-Python aes_gcm
cd aes_gcm && git checkout f3f6c5c4e0e274ff730937c90463acdfa6b5c6d7
cd ..
```

**Comment by asmw** [comment]
Please try again if you are still interested, I merged several PRs and cleaned up
